name: Bug report
description: "Use this template if you're running into bugs or other issues"
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: >-
        ## Instructions

        This is a little template to ensure enough information is provided.
        Please fill out all of the below for a nice and clean bug report!
        
        
  - type: dropdown
    id: edition
    attributes:
      label: Select what editon you are using
      options:
        - 1.8
        - 1.9 - 1.12
        - 1.13+
        
    validations:
      reqired: true

  - type: input
    id: game
    attributes:
      label: Game Version
      description: >-
        Please provide the exact game version thst is listed within the F3-Menu
      placeholder: "Example: 'fabric-loader-0.14.9-1.19.2', or 'Vanilla-1.19.2'"
    validations:
      required: true
            
  - type: textarea
    id: packs
    attributes:
      label: List of all loaded packs
      description: >-
        Provide a list of all your resource packs
      placeholder: |
        Example:
            - Faithfulx32-1.19.2
            - Nautilus3D_1.13+_V1.6
            - Default
    validations:
      required: true
      
  - type: textarea
    id: mods
    attributes:
      label: List all your installed mods
      description: >-
        Provide a list of all your installed mods
      placeholder: |
        Example:
            - Sodium-0.14.9
            - iris-0.21
      
  - type: textarea
    id: issue
    attributes:
      label: Describe your issue
      placeholder: |
        Example: sugar canes show a missing texture.
        please also provide some screenshots with the F3-Menu open
    validations:
      required: true
