name: Bug report
description: "Use this template if you're running into bugs or other issues"
labels:
  - T-bug
  - S-needs-triage
body:
  - type: markdown
    attributes:
      value: >-
        ## Instructions


        Please fill out all of the below for a nice and clean bug report

  - type: input
    id: version
    attributes:
      label: Game Version
      description: >-
        Please provide the exact game version thst is listed within the F3-Menu
      placeholder: 'fabric-loader-0.14.9-1.19.2, or Vanilla-1.19.2'
    validations:
      required: true
  - type: textarea
    id: issue
    attributes:
      label: Describe your issue
      placeholder: |
        Example: sugar canes show a missing texture.
        please also provide some screenshots with the F3-Menu open
    validations:
      required: true
  - type: textarea
    id: mods
    attributes:
      label: List all your installed mods
      description: >-
        Provide a list of all your installed mods
      placeholder: |
        Example:
            - Sodium-0.14.9
            - iris-0.21
    validations:
      required: true
  - type: textarea
    id: packs
    attributes:
      label: List of other installed packs
      description: >-
        Provide a list of all your other installed resource packs
      placeholder: |
        Example:
            - Faithfulx32-1.19.2
            - Nautilus3D-V1.6
            - Default
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional information
      description: >-
        Provide a list of any other mods you are using, along with their
        respective versions. If you have any screenshots, videos, or other
        information that you feel is necessary to explain the issue, feel free
        to attach them here.
