name: Bug report
description: "Use this template if you found a bug or other issues"
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: >-
        Please fill out all of the below to ensure enough information is provided.
        

  - type: input
    id: game
    attributes:
      label: Game Version
      description: >-
        Exact game version shown in the F3-Menu
      placeholder: "Example: 'fabric-loader-0.14.9-1.19.2', or 'Vanilla-1.19.2'"
    validations:
      required: true
      
  - type: textarea
    id: mods
    attributes:
      label: List all installed mods
      description: >-
       List all your installed mods. Leave empty if you are running vanilla.
      placeholder: |
        Example:
            - Sodium-0.14.9
            - iris-0.21
            
  - type: textarea
    id: packs
    attributes:
      label: List of all loaded packs
      description: >-
        List all your currently loaded resource packs in the same order as in-game.
      placeholder: |
        Example:
            - Faithful32-1.21.6
            - Nautilus3D-V2.4
            - Default
    validations:
      required: true
      
  - type: textarea
    id: issue
    attributes:
      label: Describe your issue
      placeholder: |
        Example: sugar canes show a missing texture.
        please also provide some screenshots with the F3-Menu visible.
    validations:
      required: true
